export const CompanyTableview = [
  {
    id: 1,
    tableHeading: "Name",
    tablesbody: [
      { tableData: "Corona School" },
      { tableData: "UBA Bank" },
      { tableData: "Star Kiddies" },
      { tableData: "Star Finance" },
      { tableData: "Glory Microfinace" },
      { tableData: "Star Kiddies" },
      { tableData: "GOE Ventures" },
      { tableData: "Star Kiddies" },
      { tableData: "Glory of God School" },
    ],
  },
  {
    id: 2,
    tableHeading: "Admin Email",
    tablesbody: [
      { tableData: "austin@coronaschool.com" },
      { tableData: "Ejike@gmail.com" },
      { tableData: "Chris@gmail.com" },
      { tableData: "Daniel@gmail.com" },
      { tableData: "Ibrahim@gmail.com" },
      { tableData: "Esther@gmail.com" },
      { tableData: "Chinaza@gmail.com" },
      { tableData: "Bola@gmail.com" },
      { tableData: "Rose@gmail.com" },
    ],
  },
  {
    id: 3,
    tableHeading: "Phone",
    tablesbody: [
      { tableData: "08011404850" },
      { tableData: "08011404850" },
      { tableData: "08011404850" },
      { tableData: "08011404850" },
      { tableData: "08011404850" },
      { tableData: "08011404850" },
      { tableData: "08011404850" },
      { tableData: "08011404850" },
      { tableData: "08011404850" },
    ],
  },
  {
    id: 4,
    tableHeading: "Location",
    tablesbody: [
      { tableDatabutton: "Lagos" },
      { tableDatabutton: "Lagos" },
      { tableDatabutton: "Lagos" },
      { tableDatabutton: "Lagos" },
      { tableDatabutton: "Lagos" },
      { tableDatabutton: "Lagos" },
      { tableDatabutton: "Lagos" },
      { tableDatabutton: "Lagos" },
      { tableDatabutton: "Lagos" },
    ],
  },
  {
    id: 4,
    tableHeading: "No. of Staff",
    tablesbody: [
      { tableDatabutton: 50 },
      { tableDatabutton: 50 },
      { tableDatabutton: 50 },
      { tableDatabutton: 50 },
      { tableDatabutton: 50 },
      { tableDatabutton: 50 },
      { tableDatabutton: 50 },
      { tableDatabutton: 50 },
      { tableDatabutton: 50 },
    ],
  },
  {
    id: 5,
    tableHeading: "Status",
    tablesbody: [
      { tableDatabutton: "ACTIVE" },
      { tableDatabutton: "ACTIVE" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "INACTIVE" },
      { tableDatabutton: "INACTIVE" },
      { tableDatabutton: "INACTIVE" },
      { tableDatabutton: "ACTIVE" },
      { tableDatabutton: "ACTIVE" },
      { tableDatabutton: "INACTIVE" },
    ],
  },
  {
    id: 6,
    tableHeading: "Action",
    tablesbody: [
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
    ],
  },
];
