export const StaffDataArray = [
  {
    id: 1,
    tableHeading: "StaffID",
    tablesbody: [
      { tableData: "ESC001" },
      { tableData: "ESC001" },
      { tableData: "ESC001" },
      { tableData: "ESC001" },
      { tableData: "ESC001" },
      { tableData: "ESC001" },
      { tableData: "ESC001" },
      { tableData: "ESC001" },
      { tableData: "ESC001" },
    ],
  },
  {
    id: 2,
    tableHeading: "Firstname",
    tablesbody: [
      { tableData: "Austin" },
      { tableData: "Austin" },
      { tableData: "Austin" },
      { tableData: "Austin" },
      { tableData: "Austin" },
      { tableData: "Austin" },
      { tableData: "Austin" },
      { tableData: "Austin" },
      { tableData: "Austin" },
    ],
  },
  {
    id: 3,
    tableHeading: "Lastname",
    tablesbody: [
      { tableData: "Godwin" },
      { tableData: "Godwin" },
      { tableData: "Godwin" },
      { tableData: "Godwin" },
      { tableData: "Godwin" },
      { tableData: "Godwin" },
      { tableData: "Godwin" },
      { tableData: "Godwin" },
      { tableData: "Godwin" },
    ],
  },
  {
    id: 4,
    tableHeading: "Position",
    tablesbody: [
      { tableDatabutton: "Product Designer" },
      { tableDatabutton: "Product Designer" },
      { tableDatabutton: "Product Designer" },
      { tableDatabutton: "Product Designer" },
      { tableDatabutton: "Product Designer" },
      { tableDatabutton: "Product Designer" },
      { tableDatabutton: "Product Designer" },
      { tableDatabutton: "Product Designer" },
      { tableDatabutton: "Product Designer" },
    ],
  },
  {
    id: 4,
    tableHeading: "Department",
    tablesbody: [
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
    ],
  },
  // {
  //   id: 5,
  //   tableHeading: "Status",
  //   tablesbody: [
  //     { tableDatabutton: "ACTIVE" },
  //     { tableDatabutton: "ACTIVE" },
  //     { tableDatabutton: "check in" },
  //     { tableDatabutton: "INACTIVE" },
  //     { tableDatabutton: "INACTIVE" },
  //     { tableDatabutton: "INACTIVE" },
  //     { tableDatabutton: "ACTIVE" },
  //     { tableDatabutton: "ACTIVE" },
  //     { tableDatabutton: "INACTIVE" },
  //   ],
  // },
  {
    id: 6,
    tableHeading: "Action",
    tablesbody: [
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
    ],
  },
];
